Add validation for InResponseTo Parameter
asgardio/asgardio-java-saml-sdk pull request #4
Opened 2020-10-07 13:55 UTC by ChamathNS

### Proposed changes in this pull request
$subject

2020-10-12 13:41 UTC, gayashanbc commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +            if (requestId.equals(inResponseToValue)) {
Is it possible for requestId to become null?
If yes, we need to prevent the NullPointer Exception here

2020-10-12 13:47 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +            if (requestId.equals(inResponseToValue)) {
Null check is done in the if statement at L369.
`session.getAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME) != null`

2020-10-12 13:57 UTC, gayashanbc approved these changes

2020-10-13 05:37 UTC, darshanasbg commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                request.getSession().setAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME, requestMessage.getID());
reuse `httpSession` variable already there?

2020-10-13 05:37 UTC, darshanasbg commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                request.getSession().setAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME, requestMessage.getID());
reuse `httpSession` variable already there?

2020-10-13 05:48 UTC, darshanasbg commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                LOGGER.log(Level.INFO, "InResponseTo Validation successful.");
`INFO` level log is too much of a detail for this type of success message..

2020-10-13 06:07 UTC, darshanasbg commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                request.getSession().setAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME, requestMessage.getID());
also, where are we add this ID when generating the authentication flow?

2020-10-13 06:43 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                request.getSession().setAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME, requestMessage.getID());
Resolved with https://github.com/asgardio/asgardio-java-saml-sdk/pull/4/commits/4f6bd870ff222c18e7597e095e50bf88636e75ed.

2020-10-13 06:43 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                request.getSession().setAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME, requestMessage.getID());
Resolved with https://github.com/asgardio/asgardio-java-saml-sdk/pull/4/commits/4f6bd870ff222c18e7597e095e50bf88636e75ed.

2020-10-13 06:43 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                LOGGER.log(Level.INFO, "InResponseTo Validation successful.");
Opted to use TRACE level instead with https://github.com/asgardio/asgardio-java-saml-sdk/pull/4/commits/4f6bd870ff222c18e7597e095e50bf88636e75ed.

2020-10-13 07:31 UTC, darshanasbg requested changes

2020-10-13 07:31 UTC, darshanasbg commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +        throw new SSOAgentException("ID validation failed.");
Better to mention `InResponseTo` ID that got failed validating.
Better to add a log here.

2020-10-13 09:17 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +        throw new SSOAgentException("ID validation failed.");
Added with https://github.com/asgardio/asgardio-java-saml-sdk/pull/4/commits/e649a02387cca7011913f78f40e82e51a160d0f3.

2020-10-13 09:18 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +    private void validateInResponseTo(LogoutResponse logoutResponse, HttpSession session) throws SSOAgentException {
Refactored with https://github.com/asgardio/asgardio-java-saml-sdk/pull/4/commits/e649a02387cca7011913f78f40e82e51a160d0f3.

2020-10-13 09:18 UTC, ChamathNS commented on io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java
> +                request.getSession().setAttribute(SSOAgentConstants.SAML2SSO.ID_ATTRIB_NAME, requestMessage.getID());
Resolved with https://github.com/asgardio/asgardio-java-saml-sdk/pull/4/commits/e649a02387cca7011913f78f40e82e51a160d0f3.

2020-10-14 03:46 UTC, darshanasbg approved these changes

2020-10-14 03:46 UTC, merged